version: "3.8"
services:
  mysql_ser:
    build: ./db
    platform: linux/amd64
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodeDB
    #  MYSQL_ROOT_HOST: '%'  # needs to be enclosed with quotes'
    ports:
      - '3306:3306'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  backend-mysql:
    depends_on:
      mysql_ser:
        condition: service_healthy
    build: .
    environment:
      MYSQL_DATABASE: nodeDB
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: mysql_ser # needs to be enclosed with quotes
    links:
      - mysql_ser
    ports:
      - 3060:3060
    restart: always
