version: '3.8'
services:
  mysqldb:
    build: ./db
    platform: linux/arm64/v8
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nodeDb
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  backend-app:
    depends_on:
      - mysqldb
    build: .
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 3060:3060
    environment:
      - DB_HOST=mysqldb
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=nodeDb
      - DB_PORT=mysqldb
    stdin_open: true
    tty: true
volumes:
  db:
